% Run a Python command in all subfolders of the specified Souce Directory

% This script will allow you to run KlustaKwik (spike detection and clustering) in python
    % srcDirectory   : Folder with all the required information of one recording session
    % folders        : Subfolders from the srcDir, each must contain 4 files:
    %    - clustering parameters: *.prm and *.prb files 
    %    - spiking data: *.dat and %.dat.mat files generated by convertNCS2Dat.m 
    %    from a subset if channels (typically 7 channels)
    % command_string : Python command that will be run in each subfolder

% The script is designed to reun in batch_KlustaKwik.m 

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% uncomment this section when running the script on its own
%% Define the parameters for batch processing of spiking data with KlustaKwik
% Define the source directory
%     Dir = 'E:\DATA Electrophysiology\';
%     srcDirectory =  uigetdir(Dir, 'Select the recording session you want to proces')
%     
% % Define the subfolders where the command needs to be run
%     folders = dir([srcDirectory '\channels*'] ); folders = {folders.name};
%     % folders = {'\channels 01-07' '\channels 06-12' '\channels 11-17' '\channels 16-22' '\channels 21-27' '\channels 26-32'};
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% Run KlustaKwik in all subfolders
% Define the python command that needs to be run
    command_string = 'klusta multichannel.prm';

    n = length(folders);

    for i = 1:n
        try
           channelsFolder = fullfile(srcDirectory, folders{i})
           cd(channelsFolder);
           status = system(command_string)
        catch
           warning(['can not perform clustering for ' channelsFolder]);
           continue
        end
    end

%% Go back to the matlab working directory
cd('C:\Users\u0105250\Documents\MATLAB')
